"""creating media history table

Revision ID: 3671c7c2b87f
Revises: eb4f38b40ce1
Create Date: 2026-07-02 01:50:18.437613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3671c7c2b87f'
down_revision: Union[str, Sequence[str], None] = 'eb4f38b40ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('clean_name', sa.String(), nullable=False),
    sa.Column('removed_tags', sa.String(), nullable=False),
    sa.Column('movement_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_history')
    # ### end Alembic commands ###
