"""Configuration table initial creation

Revision ID: 530f1c7c0c56
Revises: 
Create Date: 2026-06-27 20:51:52.847733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530f1c7c0c56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_config',
    sa.Column('id_config', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_folder', sa.String(), nullable=False),
    sa.Column('destination_folder', sa.String(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_config')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder_config')
    # ### end Alembic commands ###
