"""fix models

Revision ID: b9fcbb8186c1
Revises: 3671c7c2b87f
Create Date: 2026-07-04 05:13:26.459598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9fcbb8186c1'
down_revision: Union[str, Sequence[str], None] = '3671c7c2b87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('existents_folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folder_name', sa.String(), nullable=False),
    sa.Column('folder_location', sa.String(), nullable=False),
    sa.Column('folder_size', sa.Integer(), nullable=True),
    sa.Column('folder_files_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_name', sa.String(), nullable=False),
    sa.Column('media_description', sa.String(), nullable=True),
    sa.Column('media_category', sa.Integer(), nullable=True),
    sa.Column('media_author', sa.String(), nullable=True),
    sa.Column('media_magazine', sa.String(), nullable=True),
    sa.Column('media_episodes', sa.Integer(), nullable=True),
    sa.Column('media_ovas', sa.Integer(), nullable=True),
    sa.Column('media_movies', sa.Integer(), nullable=True),
    sa.Column('media_novels', sa.Integer(), nullable=True),
    sa.Column('media_seasons', sa.Integer(), nullable=True),
    sa.Column('media_status', sa.String(), nullable=True),
    sa.Column('media_released_at', sa.DateTime(), nullable=True),
    sa.Column('media_ended_at', sa.DateTime(), nullable=True),
    sa.Column('media_nsfw', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('existents_folder')
    op.drop_table('medias')
    op.drop_constraint(None, 'media_episodes', type_='foreignkey')
    op.create_foreign_key(None, 'media_episodes', 'media', ['media_id'], ['id'])
    op.drop_constraint(None, 'media_genre', type_='foreignkey')
    op.create_foreign_key(None, 'media_genre', 'media', ['media_id'], ['id'])
    op.add_column('media_history', sa.Column('origin_media', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_history', 'origin_media')
    op.drop_constraint(None, 'media_genre', type_='foreignkey')
    op.create_foreign_key(None, 'media_genre', 'medias', ['media_id'], ['id'])
    op.drop_constraint(None, 'media_episodes', type_='foreignkey')
    op.create_foreign_key(None, 'media_episodes', 'medias', ['media_id'], ['id'])
    op.create_table('medias',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('media_name', sa.VARCHAR(), nullable=False),
    sa.Column('media_description', sa.VARCHAR(), nullable=True),
    sa.Column('media_category', sa.INTEGER(), nullable=True),
    sa.Column('media_author', sa.VARCHAR(), nullable=True),
    sa.Column('media_magazine', sa.VARCHAR(), nullable=True),
    sa.Column('media_episodes', sa.INTEGER(), nullable=True),
    sa.Column('media_ovas', sa.INTEGER(), nullable=True),
    sa.Column('media_movies', sa.INTEGER(), nullable=True),
    sa.Column('media_novels', sa.INTEGER(), nullable=True),
    sa.Column('media_seasons', sa.INTEGER(), nullable=True),
    sa.Column('media_status', sa.VARCHAR(), nullable=True),
    sa.Column('media_released_at', sa.DATETIME(), nullable=True),
    sa.Column('media_ended_at', sa.DATETIME(), nullable=True),
    sa.Column('media_nsfw', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('existents_folder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('folder_name', sa.VARCHAR(), nullable=False),
    sa.Column('folder_location', sa.VARCHAR(), nullable=False),
    sa.Column('folder_size', sa.INTEGER(), nullable=True),
    sa.Column('folder_files_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('media')
    op.drop_table('existents_folders')
    # ### end Alembic commands ###
