"""add media-episodes relationship and new tables

Revision ID: eb4f38b40ce1
Revises: 530f1c7c0c56
Create Date: 2026-07-01 15:19:05.477167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb4f38b40ce1'
down_revision: Union[str, Sequence[str], None] = '530f1c7c0c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin_folder', sa.String(), nullable=False),
    sa.Column('destination_folder', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('existents_folder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('folder_name', sa.String(), nullable=False),
    sa.Column('folder_location', sa.String(), nullable=False),
    sa.Column('folder_size', sa.Integer(), nullable=True),
    sa.Column('folder_files_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('medias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_name', sa.String(), nullable=False),
    sa.Column('media_description', sa.String(), nullable=True),
    sa.Column('media_category', sa.Integer(), nullable=True),
    sa.Column('media_author', sa.String(), nullable=True),
    sa.Column('media_magazine', sa.String(), nullable=True),
    sa.Column('media_episodes', sa.Integer(), nullable=True),
    sa.Column('media_ovas', sa.Integer(), nullable=True),
    sa.Column('media_movies', sa.Integer(), nullable=True),
    sa.Column('media_novels', sa.Integer(), nullable=True),
    sa.Column('media_seasons', sa.Integer(), nullable=True),
    sa.Column('media_status', sa.String(), nullable=True),
    sa.Column('media_released_at', sa.DateTime(), nullable=True),
    sa.Column('media_ended_at', sa.DateTime(), nullable=True),
    sa.Column('media_nsfw', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('removable_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_name', sa.String(), nullable=False),
    sa.Column('ignore_tag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('episode_title', sa.String(), nullable=False),
    sa.Column('episode_synopsis', sa.String(), nullable=True),
    sa.Column('episode_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_genre',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['medias.id'], ),
    sa.PrimaryKeyConstraint('media_id', 'genre_id')
    )
    op.drop_table('folder_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_config',
    sa.Column('id_config', sa.INTEGER(), nullable=False),
    sa.Column('origin_folder', sa.VARCHAR(), nullable=False),
    sa.Column('destination_folder', sa.VARCHAR(), nullable=False),
    sa.Column('active', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id_config')
    )
    op.drop_table('media_genre')
    op.drop_table('media_episodes')
    op.drop_table('removable_tags')
    op.drop_table('medias')
    op.drop_table('genres')
    op.drop_table('existents_folder')
    op.drop_table('configurations')
    # ### end Alembic commands ###
